### ISSUE TITLE
Add `first_value`/`last_value` reducers.

### ISSUE THREAD

**Issue by izulin** [pathwaycom/pathway#40]
**Is your feature request related to a problem? Please describe.**

Add a reducer that keeps the first/last `system_time` value.

**Comment by dxtrous** [comment]
Thanks - this is a partial duplicate of #18 ?

**Comment by izulin** [comment]
> Thanks - this is a partial duplicate of #18 ?

not really -- system_time vs data_time (time column)

**Comment by izulin** [comment]
available in 0.9.0

**Comment by jagatsingh** [comment]
This will be a great enhancement as it is common use case in time series analytics.

**Comment by KamilPiechowiak** [comment]
Hey, @jagatsingh,
this issue is already completed. We have [`earliest`](https://pathway.com/developers/api-docs/reducers#pathway.reducers.earliest) and [`latest`](https://pathway.com/developers/api-docs/reducers#pathway.reducers.latest) reducers. They return values with the lowest/highest processing time respectively.
